spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: skqkrl01

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create # create, none, validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
    open-in-view: false
    #    open-in-view: false

  # 한글 깨짐 방지
  #Encoding UTF-8
  sql:
    init:
      encoding: utf-8

  devtools:
    # Auto Restart
    restart:
      enabled: true

  # 개발에만 사용 운영에는 제거
  thymeleaf:
    cache: false

# 파일관련 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

itemImgLocation: E:/shop/item
uploadPath: file:///E:/shop/


logging:
  level:
    sql: trace

